
import React, { useState, useEffect } from 'react';
import { Utensils, Calendar, Printer, FolderHeart, Settings, Upload, X } from 'lucide-react';
import { TabButton, ClayButton, ClayInput } from './components/UIComponents';
import CalorieCalculator from './components/CalorieCalculator';
import SchedulePlanner from './components/SchedulePlanner';
import RetroPrinter from './components/RetroPrinter';
import HistoryFolder from './components/HistoryFolder';
import { FoodItem, ScheduleItem, DailyLog, TabView, Theme, Language, UserProfile, Translation, Mood } from './types';

const LOCALE_EN: Translation = {
  dietTracker: "Diet Tracker",
  dailyPlan: "Daily Plan",
  archives: "Archives",
  print: "Print",
  settings: "Settings",
  total: "Total",
  add: "Add",
  analyze: "Analyze",
  noFood: "No food logged yet",
  noTask: "No tasks planned",
  placeholderFood: "Food name (e.g. Apple)",
  placeholderWeight: "g",
  placeholderTask: "What's the plan?",
  saveToFolder: "Saved to Daily Folder!",
  printAnother: "Print Another Copy",
  fuel: "Fuel",
  plan: "Plan",
  generatedBy: "Generated by NootNote",
  settingsTitle: "Settings",
  username: "Username",
  avatar: "Avatar",
  theme: "Theme",
  language: "Language",
  save: "Save",
  dragHint: "You can drag the note!",
  files: "Files",
  loading: "Thinking...",
  foodName: "Food Name",
  weightAmt: "Weight",
  delete: "Delete",
  confirmDelete: "Are you sure you want to delete the selected records? This will also clear your current workspace.",
  viewDetails: "View Details",
  mood: "Mood",
  moodHappy: "Happy",
  moodNeutral: "Neutral",
  moodTired: "Tired",
  moodEnergetic: "Energetic",
  moodRelax: "Relaxed",
  work: "Work",
  fun: "Fun",
  meal: "Meal",
  rest: "Rest",
  todayMood: "Today's Mood",
  clickToView: "Click to view",
  select: "Select",
  cancel: "Cancel",
  deleteSelected: "Delete Selected",
  itemsSelected: "items selected"
};

const LOCALE_ZH: Translation = {
  dietTracker: "饮食追踪",
  dailyPlan: "每日计划",
  archives: "归档记录",
  print: "打印",
  settings: "设置",
  total: "总计",
  add: "添加",
  analyze: "分析",
  noFood: "暂无饮食记录",
  noTask: "暂无计划",
  placeholderFood: "食物名称 (如: 苹果)",
  placeholderWeight: "克",
  placeholderTask: "接下来做什么？",
  saveToFolder: "已保存至文件夹！",
  printAnother: "再打印一份",
  fuel: "能量补给",
  plan: "日程安排",
  generatedBy: "NootNote生成",
  settingsTitle: "设置",
  username: "用户名",
  avatar: "头像",
  theme: "主题颜色",
  language: "语言",
  save: "保存",
  dragHint: "便利贴可以拖拽哦！",
  files: "文件",
  loading: "计算中...",
  foodName: "食物名称",
  weightAmt: "重量(克)",
  delete: "删除",
  confirmDelete: "确定要删除选中的记录吗？这同时会清空当前的饮食和计划内容。",
  viewDetails: "查看详情",
  mood: "心情",
  moodHappy: "开心",
  moodNeutral: "平淡",
  moodTired: "疲惫",
  moodEnergetic: "元气满满",
  moodRelax: "轻松",
  work: "工作",
  fun: "娱乐",
  meal: "用餐",
  rest: "休息",
  todayMood: "今日心情",
  clickToView: "点击查看详情",
  select: "选择",
  cancel: "取消",
  deleteSelected: "删除选中",
  itemsSelected: "项已选择"
};

const THEMES = {
  classic: { black: '#2C2C2C', white: '#FDFDFD', accent: '#FF7043', danger: '#E53935', gray: '#E0E0E0', bg: '#F2F5F8', shadowD: '#b8b9be', shadowL: '#ffffff' },
  ocean: { black: '#1A3A4A', white: '#F0F8FF', accent: '#4DB6AC', danger: '#EF5350', gray: '#B0BEC5', bg: '#E1F5FE', shadowD: '#90a4ae', shadowL: '#ffffff' },
  sakura: { black: '#4A2C36', white: '#FFF0F5', accent: '#FF80AB', danger: '#FF4081', gray: '#E1BEE7', bg: '#FCE4EC', shadowD: '#f48fb1', shadowL: '#ffffff' },
  forest: { black: '#1B5E20', white: '#F1F8E9', accent: '#8BC34A', danger: '#D32F2F', gray: '#C5E1A5', bg: '#DCEDC8', shadowD: '#aed581', shadowL: '#ffffff' },
  lavender: { black: '#4A235A', white: '#F5EEF8', accent: '#AF7AC5', danger: '#E74C3C', gray: '#D7BDE2', bg: '#EBDEF0', shadowD: '#c39bd3', shadowL: '#ffffff' },
  coffee: { black: '#3E2723', white: '#FFF8E1', accent: '#8D6E63', danger: '#D84315', gray: '#D7CCC8', bg: '#EFEBE9', shadowD: '#a1887f', shadowL: '#ffffff' }
};

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<TabView>('calculator');
  const [foods, setFoods] = useState<FoodItem[]>([]);
  const [schedule, setSchedule] = useState<ScheduleItem[]>([]);
  const [history, setHistory] = useState<DailyLog[]>([]);
  const [mood, setMood] = useState<Mood | undefined>('happy');
  
  // Settings State
  const [showSettings, setShowSettings] = useState(false);
  const [language, setLanguage] = useState<Language>('en');
  const [theme, setTheme] = useState<Theme>('classic');
  const [user, setUser] = useState<UserProfile>({ name: 'NootUser', avatar: null });

  const t = language === 'zh' ? LOCALE_ZH : LOCALE_EN;

  // Load data
  useEffect(() => {
    const savedHist = localStorage.getItem('nootnote-history');
    if (savedHist) setHistory(JSON.parse(savedHist));

    const savedSettings = localStorage.getItem('nootnote-settings');
    if (savedSettings) {
      const parsed = JSON.parse(savedSettings);
      setLanguage(parsed.language || 'en');
      setTheme(parsed.theme || 'classic');
      setUser(parsed.user || { name: 'NootUser', avatar: null });
    }
  }, []);

  // Update CSS Variables for Theme
  useEffect(() => {
    const t = THEMES[theme];
    const root = document.documentElement;
    root.style.setProperty('--color-black', t.black);
    root.style.setProperty('--color-white', t.white);
    root.style.setProperty('--color-accent', t.accent);
    root.style.setProperty('--color-danger', t.danger);
    root.style.setProperty('--color-gray', t.gray);
    root.style.setProperty('--color-bg', t.bg);
    root.style.setProperty('--shadow-dark', t.shadowD);
    root.style.setProperty('--shadow-light', t.shadowL);
    
    // Save settings
    localStorage.setItem('nootnote-settings', JSON.stringify({ language, theme, user }));
  }, [theme, language, user]);

  const handleSaveLog = (quote: string) => {
    const newLog: DailyLog = {
      id: crypto.randomUUID(),
      date: new Date().toISOString(),
      totalCalories: foods.reduce((acc, curr) => acc + curr.calories, 0),
      foods: [...foods],
      schedule: [...schedule],
      mood: mood,
      quote: quote
    };

    const updatedHistory = [...history, newLog];
    setHistory(updatedHistory);
    localStorage.setItem('nootnote-history', JSON.stringify(updatedHistory));
  };

  const handleClearCurrentData = () => {
    setFoods([]);
    setSchedule([]);
    setMood('happy');
  };

  const handleAvatarUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setUser(prev => ({ ...prev, avatar: reader.result as string }));
      };
      reader.readAsDataURL(file);
    }
  };

  return (
    <div className="min-h-screen bg-pingu-bg flex justify-center overflow-hidden transition-colors duration-300">
      <div className="w-full max-w-md bg-white h-screen shadow-2xl relative flex flex-col">
        
        {/* Header */}
        <header className="pt-8 pb-4 px-6 bg-white z-10 flex justify-between items-center">
          <div className="flex items-center justify-center relative">
            <div className="relative w-10 h-10 rounded-full overflow-hidden border-2 border-pingu-black bg-pingu-black flex items-center justify-center cursor-pointer transition-transform hover:scale-105" onClick={() => setShowSettings(true)}>
               {user.avatar ? (
                 <img src={user.avatar} alt="avatar" className="w-full h-full object-cover" />
               ) : (
                 <>
                    <div className="w-6 h-4 bg-pingu-white rounded-full relative top-[1px]">
                      <div className="absolute top-1 left-1 w-1 h-1 bg-black rounded-full"></div>
                      <div className="absolute top-1 right-1 w-1 h-1 bg-black rounded-full"></div>
                    </div>
                    <div className="absolute bottom-[-2px] w-3 h-3 bg-pingu-orange rotate-45 rounded-sm"></div>
                 </>
               )}
            </div>
            <div className="pl-4">
               <h1 className="text-3xl font-black tracking-tight text-pingu-black leading-none">NootNote</h1>
               <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">{t.generatedBy.split(' ')[1] || 'Planner'}</p>
            </div>
          </div>
          <button onClick={() => setShowSettings(true)} className="text-gray-400 hover:text-pingu-black hover:rotate-90 transition-all">
            <Settings size={24} />
          </button>
        </header>

        {/* Settings Modal */}
        {showSettings && (
          <div className="absolute inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-end sm:items-center justify-center animate-in fade-in duration-300">
            <div className="bg-white w-full max-w-md rounded-t-3xl sm:rounded-3xl p-6 shadow-2xl h-[85vh] sm:h-auto overflow-y-auto animate-in slide-in-from-bottom-10 custom-scrollbar">
               <div className="flex justify-between items-center mb-6 sticky top-0 bg-white z-10 pb-2 border-b border-gray-100">
                 <h2 className="text-2xl font-black">{t.settingsTitle}</h2>
                 <button onClick={() => setShowSettings(false)} className="bg-gray-100 p-2 rounded-full hover:bg-gray-200"><X size={20} /></button>
               </div>
               
               <div className="space-y-6 pb-10">
                  {/* User */}
                  <div className="space-y-2">
                    <label className="font-bold text-sm text-gray-500 uppercase tracking-wide">{t.username}</label>
                    <ClayInput value={user.name} onChange={(e) => setUser({...user, name: e.target.value})} />
                  </div>
                  <div className="space-y-2">
                    <label className="font-bold text-sm text-gray-500 uppercase tracking-wide">{t.avatar}</label>
                    <div className="flex gap-4 items-center">
                      <div className="w-20 h-20 rounded-full bg-gray-100 overflow-hidden border-2 border-dashed border-gray-300 flex items-center justify-center relative group">
                        {user.avatar ? <img src={user.avatar} className="w-full h-full object-cover" /> : <div className="text-gray-300 text-2xl font-bold">?</div>}
                        <div className="absolute inset-0 bg-black/20 hidden group-hover:flex items-center justify-center text-white font-bold text-xs">Change</div>
                      </div>
                      <label className="cursor-pointer bg-pingu-black text-white px-6 py-3 rounded-xl font-bold text-sm hover:bg-gray-800 transition-colors flex items-center gap-2 shadow-lg shadow-gray-300">
                        <Upload size={16} /> Upload
                        <input type="file" className="hidden" accept="image/*" onChange={handleAvatarUpload} />
                      </label>
                    </div>
                  </div>

                  {/* Language */}
                  <div className="space-y-2">
                    <label className="font-bold text-sm text-gray-500 uppercase tracking-wide">{t.language}</label>
                    <div className="flex gap-2 bg-gray-100 p-1 rounded-2xl">
                       <button onClick={() => setLanguage('en')} className={`flex-1 py-3 rounded-xl font-bold transition-all ${language === 'en' ? 'bg-white text-black shadow-md' : 'text-gray-400'}`}>English</button>
                       <button onClick={() => setLanguage('zh')} className={`flex-1 py-3 rounded-xl font-bold transition-all ${language === 'zh' ? 'bg-white text-black shadow-md' : 'text-gray-400'}`}>中文</button>
                    </div>
                  </div>

                  {/* Theme */}
                  <div className="space-y-2">
                    <label className="font-bold text-sm text-gray-500 uppercase tracking-wide">{t.theme}</label>
                    <div className="grid grid-cols-3 gap-3">
                      {(Object.keys(THEMES) as Theme[]).map((th) => (
                        <button 
                          key={th} 
                          onClick={() => setTheme(th)}
                          className={`h-14 rounded-xl border-2 flex flex-col items-center justify-center transition-all relative overflow-hidden ${theme === th ? 'border-black ring-2 ring-black/10 scale-105' : 'border-transparent opacity-80 hover:opacity-100'}`}
                          style={{ backgroundColor: THEMES[th].bg }}
                        >
                           <span className="text-[10px] font-bold uppercase z-10 mix-blend-darken">{th}</span>
                           <div className="absolute bottom-0 left-0 w-full h-2" style={{ backgroundColor: THEMES[th].accent }}></div>
                        </button>
                      ))}
                    </div>
                  </div>
                  
                  <ClayButton onClick={() => setShowSettings(false)} className="w-full mt-6">{t.save}</ClayButton>
               </div>
            </div>
          </div>
        )}

        {/* Main Content Area */}
        <main className="flex-1 overflow-y-auto px-6 pb-32 relative scroll-smooth custom-scrollbar">
           {activeTab === 'calculator' && <CalorieCalculator foods={foods} setFoods={setFoods} t={t} />}
           {activeTab === 'schedule' && <SchedulePlanner schedule={schedule} setSchedule={setSchedule} mood={mood} setMood={setMood} t={t} />}
           {activeTab === 'printer' && <RetroPrinter foods={foods} schedule={schedule} onSave={handleSaveLog} t={t} language={language} user={user} mood={mood} />}
           {activeTab === 'history' && <HistoryFolder history={history} setHistory={setHistory} t={t} user={user} language={language} onClearData={handleClearCurrentData} />}
        </main>

        {/* Floating Bottom Navigation */}
        <nav className="absolute bottom-6 left-6 right-6 z-40">
          <div className="bg-white/90 backdrop-blur-md rounded-3xl shadow-clay p-2 flex justify-around border border-white ring-1 ring-gray-100">
            <TabButton 
              active={activeTab === 'calculator'} 
              onClick={() => setActiveTab('calculator')} 
              icon={<Utensils size={24} />} 
              label={t.dietTracker}
            />
            <TabButton 
              active={activeTab === 'schedule'} 
              onClick={() => setActiveTab('schedule')} 
              icon={<Calendar size={24} />} 
              label={t.dailyPlan}
            />
            <TabButton 
              active={activeTab === 'printer'} 
              onClick={() => setActiveTab('printer')} 
              icon={<Printer size={24} />} 
              label={t.print}
            />
            <TabButton 
              active={activeTab === 'history'} 
              onClick={() => setActiveTab('history')} 
              icon={<FolderHeart size={24} />} 
              label={t.files}
            />
          </div>
        </nav>

      </div>
    </div>
  );
};

export default App;
